name: Build and publish library

on:
  push:
    branches: [main]
    paths-ignore:
      - README.md
  pull_request:
    branches: [main]
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Gradle compile and test
        run: ./gradlew clean test

      - name: Create distribution
        run: ./gradlew publishMavenKotlinPublicationToBuildDirRepoRepository

#      - name: Publish artefacts
#        uses: actions/